=== bghrt/reynolds/legacy/find/newbooks/archive/rss/schema/month_schema.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
    <xs:element name="month" type="MonthType"/>
    <xs:complexType name="MonthType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="link" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="language" type="xs:string"/>
            <xs:element name="lastBuildDate" type="xs:string"/>
            <xs:element name="item" type="ItemType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ItemType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="link" type="xs:string"/>
            <xs:element name="callno" type="xs:string"/>
            <xs:element name="collection" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="rec" type="xs:string"/>
        <xs:attribute name="month" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== bghrt/reynolds/legacy/find/newbooks/archive/rss/xml/2009/sept.xml
<?xml version='1.0' encoding='iso-8859-1' ?>
<month xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://library.Reynolds.edu/find/new# http://library.Reynolds.edu/find/new/archive/rss/schema/month_schema.xsd' >
		<title>New Books at Reynolds Library</title>
		<link>http://library.Reynolds.edu/find/new/default.html</link>
		<description>RSS feed for new and recommended books at J. Sargeant Reynolds Community College Library</description>
		<language>en-us</language>
		<lastBuildDate>6/2/2010 11:59:31 AM</lastBuildDate>
		<item rec='no' month='Sept'>
			<title>Descartes' bones :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1600694</link>
			<callno>B1875 .S495 2008</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>The philosophers' quarrel :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1602614</link>
			<callno>B2137 .Z37 2009</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Philosophy in turbulent times :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1602615</link>
			<callno>B2421 .R6813 2008</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>The whole death catalog :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1599655</link>
			<callno>BD444 .S383 2009</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>What makes us human? /</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1600333</link>
			<callno>BD450 .W4877 2007</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Concise rules of APA style.</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1600690</link>
			<callno>BF76.7 .C66 2010</callno>
			<collection>Reference Desk</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Handbook of emotions /</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1601284</link>
			<callno>BF561 .H35 2008</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>The age of empathy :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1602898</link>
			<callno>BF575.E55 W3 2009</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Loneliness :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1599364</link>
			<callno>BF575.L7 C23 2008</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Avenues for success :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1602904</link>
			<callno>BF637.S8 B477 2001</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Bright-sided :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1597302</link>
			<callno>BF698.35.O57 E37 2009</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>The dream encyclopedia /</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1600697</link>
			<callno>BF1091 .L53 2009</callno>
			<collection>Reference</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Cruelty :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1602261</link>
			<callno>BJ1535.C7 T38 2009</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Life inc. :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1597316</link>
			<callno>BJ1581.2 .R865 2009</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Bad faith :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1599952</link>
			<callno>BL238 .K74 2007</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Apocalypse :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1602333</link>
			<callno>BL501 .H35 2009</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Death gods :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1602346</link>
			<callno>BL545 .A24 2009</callno>
			<collection>Reference</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Myths from Mesopotamia :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1599370</link>
			<callno>BL1620 .M98 2008</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>The Bible and the Qur'an /</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1599953</link>
			<callno>BP134.B4 J613 2002</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>The everything understanding Islam book :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1599965</link>
			<callno>BP161.2 .D63 2009</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Islam /</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1599977</link>
			<callno>BP161.3 .I723 2009</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Inside jihadism :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1599975</link>
			<callno>BP182 .K52 2009</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>A people's history of Christianity :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1599379</link>
			<callno>BR148 .B37 2009</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>After the baby boomers :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1602237</link>
			<callno>BV4529.2 .W88 2007</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>The Shaker village /</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1601287</link>
			<callno>BX9784 .B53 2008</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>The world's best memoir writing :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1601310</link>
			<callno>CT25 .W665 2007</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>The encyclopedia of sixties cool :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1599963</link>
			<callno>CT120 .S76 2007</callno>
			<collection>Reference</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>The crusades, Christianity, and Islam /</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1598764</link>
			<callno>D157 .R536 2008</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>World War One /</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1599658</link>
			<callno>D521 .S855 2009</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Daily life in Anglo-Saxon England /</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1602345</link>
			<callno>DA152 .C76 2009</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>The English Civil War :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1601283</link>
			<callno>DA415 .P87 2006</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Culture and customs of the Czech Republic and Slovakia /</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1602344</link>
			<callno>DB2035 .C73 2006</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Culture and customs of France /</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1602338</link>
			<callno>DC33.7 .H26 2006</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>War &amp; genocide :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1601299</link>
			<callno>DD256.5 .B3916 2009</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>The fires of Vesuvius :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1597707</link>
			<callno>DG70.P7 B43 2008</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Ancient Rome :</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1601610</link>
			<callno>DG311 .B34 2006</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>Culture and customs of the Baltic states /</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1602343</link>
			<callno>DK502.6 .O24 2006</callno>
			<collection>Circulating Collection</collection>
		</item>
		<item rec='no' month='Sept'>
			<title>A history of Islamic societies /</title>
			<link>http://vccslinc.vccs.edu/F?func=find-c&amp;ccl_term=sys=1601615</link>
